[package]
name = "json-schema-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
schemars = { version = "0.8.21", features = ["chrono"] }
serde_json = "1.0.117"
